version: 1.0.{build}
image: Visual Studio 2019
build_script:
- ps: $([System.DateTime]::Now)
- ps: |
    Remove-Item -Path C:\Ruby* -Recurse -Force -Confirm:$false
    Remove-Item -Path C:\Python* -Recurse -Force -Confirm:$false
    Remove-Item -Path C:\go* -Recurse -Force -Confirm:$false
    Remove-Item -Path C:\Q* -Recurse -Force -Confirm:$false
    Remove-Item -Path C:\cygwin* -Recurse -Force -Confirm:$false
    Remove-Item -Path C:\Miniconda* -Recurse -Force -Confirm:$false
    Remove-Item -Path C:\OpenSSL* -Recurse -Force -Confirm:$false
    Get-ChildItem -Path C:\
- ps: $([System.DateTime]::Now)
- ps: |
    (Get-CimInstance -ClassName Win32_LogicalDisk | Select-Object -Property DeviceID,@{'Name' = 'FreeSpace (GB)'; Expression= { [int]($_.FreeSpace / 1GB) }} | Measure-Object -Property 'FreeSpace (GB)' -Sum).Sum
test: off
#on_finish:
#- ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
