version: 1.0.{build}
image: Visual Studio 2019
build_script:
- ps: |
    Get-ChildItem -Path . -Recurse -Filter "Ruby*" | ForEach-Object { Remove-Item -Path $_.FullName -Confirm:$false -Force -Recurse }
    Get-ChildItem -Path . -Recurse -Filter "Python*" | ForEach-Object { Remove-Item -Path $_.FullName -Confirm:$false -Force -Recurse }
    Get-ChildItem -Path . -Recurse -Filter "go*" | ForEach-Object { Remove-Item -Path $_.FullName -Confirm:$false -Force -Recurse }
    Get-ChildItem -Path . -Recurse -Filter "Qt*" | ForEach-Object { Remove-Item -Path $_.FullName -Confirm:$false -Force -Recurse }
    Get-ChildItem -Path . -Recurse -Filter "cygwin*" | ForEach-Object { Remove-Item -Path $_.FullName -Confirm:$false -Force -Recurse }
    Get-ChildItem -Path . -Recurse -Filter "Miniconda*" | ForEach-Object { Remove-Item -Path $_.FullName -Confirm:$false -Force -Recurse }
    Get-ChildItem -Path . -Recurse -Filter "OpenSSL*" | ForEach-Object { Remove-Item -Path $_.FullName -Confirm:$false -Force -Recurse }
test: off
#on_finish:
#- ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
